const CREATE_ACTIVITY = "CREATE_ACTIVITY";
const GET_ALL_TRAINERS = "GET_ALL_TRAINERS";
const GET_ALL_USERS = "GET_ALL_USERS";
const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
const VALIDATE_USER_IS_LOGGED = "VALIDATE_USER_IS_LOGGED";
const REGISTER_USER_WITH_EMAIL_AND_PASS = "REGISTER_USER_WITH_EMAIL_AND_PASS";
const SIGN_IN_USER = "SIGN_IN_USER";
const USER_SIGN_OUT = "USER_SIGN_OUT";
const REQUEST_POST = "REQUEST_POST";
const RECEIVED_POST = "RECEIVED_POST";

export {
  CREATE_ACTIVITY,
  REQUEST_POST,
  RECEIVED_POST,
  GET_ALL_TRAINERS,
  REGISTER_USER_WITH_EMAIL_AND_PASS,
  VALIDATE_USER_IS_LOGGED,
  LOGIN_WITH_GOOGLE,
  SIGN_IN_USER,
  USER_SIGN_OUT,
  GET_ALL_USERS,
};
